openapi: 3.0.1
info:
  title: Workleap Extensions Configuration Secrets
  description: .NET library allowing to store configuration values in Azure Key Vault Secrets.
  x-cortex-git:
    github:
      alias: gsoft-inc
      repository: gsoft-inc/wl-extensions-configuration-secrets
  x-cortex-tag: service-wl-extensions-configuration-secrets
  x-cortex-type: library
  x-cortex-slack:
    channels:
    - name: internal-dev-platform
      notificationsEnabled: true
  x-cortex-owners:
    - name: team-internal-developer-platform-backend
      type: GROUP
      provider: CORTEX
  x-cortex-link:
    - name: Documentation
      type: documentation
      url: https://gsoftdev.atlassian.net/wiki/spaces/TEC/pages/3560800503
    - type: cortex
      url: https://github.com/gsoft-inc/wl-extensions-configuration-secrets/blob/main/.cortex/catalog/service-wl-extensions-configuration-secrets.yaml
      name: Edit current Cortex entity in GitHub

