name: CI

on:
  pull_request:
    branches: ["main"]

  push:
    branches:
      - "renovate/**"
  
jobs:
  main:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on: [ windows-2022, ubuntu-24.04 ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - run: ./Build.ps1
        shell: pwsh
